name: Build and Publish

on:
  push:
    branches:
      - main  # 修改为您主要的分支名称

jobs:
  build:
    runs-on: windows-latest  # 使用最新版本的 Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '8'  # 修改为您项目所需的 Java 版本

    - name: Build with Gradle
      run: ./gradlew.bat build  # 修改为您的 gradlew 文件名称

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Installer
        path: build/libs/Installer-1.0-all.jar  # 修改为您构建生成的 Jar 文件路径

